include(FetchContent)

function(add_external_library name dir repo tag)
	if(EXISTS ${dir}/CMakeLists.txt)
		message(STATUS "Using existing ${name} at ${dir}")
	else()
		message(STATUS "Cloning ${name} to ${dir}")
		if(tag)
			FetchContent_Declare(${name} GIT_REPOSITORY ${repo} GIT_TAG ${tag} SOURCE_DIR ${dir})
		else()
			FetchContent_Declare(${name} GIT_REPOSITORY ${repo} SOURCE_DIR ${dir})
		endif()
		FetchContent_MakeAvailable(${name})
	endif()
endfunction()